CREATE PROCEDURE CRE_USER_PR
(
    @P_USER_CODE NVARCHAR(25),
    @P_NAME NVARCHAR(50),
    @P_EMAIL NVARCHAR(30),
    @P_PASSWORD NVARCHAR(20),
    @P_BIRTH_DATE DATETIME,
    @P_STATUS NVARCHAR(2),
    @P_PHONE_NUMBER INT
)
AS
BEGIN
    INSERT INTO tblUsers(Created, UserCode, Name, Email, Password, BirthDate, Status, PhoneNumber)
    VALUES(GETDATE(), @P_USER_CODE, @P_NAME, @P_EMAIL, @P_PASSWORD, @P_BIRTH_DATE, @P_STATUS, @P_PHONE_NUMBER);
END
GO